version: "3"
services:
  backend:
    image: cands_backend
    build: ./CandSAPI
    container_name: api
    ports: 
      - 8000:8000
    volumes:
      - ./CandSAPI:/app
    environment:
      DATABASE_URL: postgres://postgres:password@db/postgres
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: cands_frontend
    build: ./countries_and_states_ts
    container_name: fe
    ports: 
      - 3000:3000
    volumes:
      - ./countries_and_states_ts:/app
    depends_on: 
      - backend
  db:
    image: postgres:15
    container_name: db
    # look into what this means
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    user: postgres
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    ports:
      - 5432:5432

