# Generated by Django 3.2.24 on 2024-03-06 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='XX', max_length=2)),
                ('name', models.CharField(default='Empty', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='XX', max_length=2)),
                ('name', models.CharField(default='Empty', max_length=60)),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='csapi.country')),
            ],
        ),
    ]
